# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/tecno/CK8n/setup-makefiles.sh


# SEPolicy for AIDL Fingerprint HAL
BOARD_VENDOR_SEPOLICY_DIRS += device/tecno/CK8n/sepolicy/vendor
